export const DEFAULT_CONTENT: Record<string, unknown> = {
  announcement_bar: {
    visible: true,
    items_en: [
      'Free delivery on orders over 500 EGP',
      'Easy 7-day returns',
      'Cash on delivery — all governorates',
      'Quality guaranteed',
    ],
    items_ar: [
      'توصيل مجاني فوق ٥٠٠ جنيه',
      'إرجاع مجاني خلال ٧ أيام',
      'دفع عند الاستلام — جميع المحافظات',
      'ضمان الجودة',
    ],
    bg_color: '#1a1a18',
    text_color: '#FAF9F7',
  },
  hero_slides: [
    {
      image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=1920&q=80',
      tag_en: 'New Collection', tag_ar: 'مجموعة جديدة',
      heading1: 'Wear What', heading2: 'Moves You',
      sub_en: 'Accessories for the modern Egyptian woman',
      sub_ar: 'إكسسوارات للمرأة المصرية العصرية',
      cta_en: 'Shop Now', cta_ar: 'تسوق الآن', cta_href: '/products',
    },
    {
      image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=1920&q=80',
      tag_en: 'Necklaces', tag_ar: 'قلادات',
      heading1: 'Effortless', heading2: 'Elegance',
      sub_en: 'Statement pieces for every occasion',
      sub_ar: 'قطع مميزة لكل مناسبة',
      cta_en: 'Shop Now', cta_ar: 'تسوق الآن', cta_href: '/products?category=necklaces',
    },
    {
      image: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=1920&q=80',
      tag_en: 'Bracelets', tag_ar: 'أساور',
      heading1: 'Golden', heading2: 'Moments',
      sub_en: 'Stack, layer, and express yourself',
      sub_ar: 'صففي، طبقي، وعبّري عن نفسك',
      cta_en: 'Shop Now', cta_ar: 'تسوق الآن', cta_href: '/products?category=bracelets',
    },
  ],
  nav_categories: [
    { slug: 'bracelets', en: 'Bracelets', ar: 'أساور' },
    { slug: 'necklaces', en: 'Necklaces', ar: 'قلادات' },
    { slug: 'rings',     en: 'Rings',     ar: 'خواتم' },
    { slug: 'sunglasses',en: 'Sunglasses',ar: 'نظارات' },
  ],
  trust_badges: [
    { icon: 'CreditCard', en: 'Cash on Delivery', ar: 'دفع عند الاستلام' },
    { icon: 'Truck',      en: 'Ships Nationwide', ar: 'شحن لكل مصر' },
    { icon: 'Shield',     en: 'Quality Guarantee', ar: 'ضمان الجودة' },
    { icon: 'Phone',      en: '7-Day Support',    ar: 'خدمة عملاء ٧ أيام' },
  ],
  categories_section: {
    tag_en: 'Shop by Category', tag_ar: 'تسوق حسب الفئة',
    title_en: 'Our Collections', title_ar: 'مجموعاتنا',
    items: [
      { slug: 'bracelets', en: 'Bracelets', ar: 'أساور', image: 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?w=800&q=80' },
      { slug: 'necklaces', en: 'Necklaces', ar: 'قلادات', image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80' },
      { slug: 'rings',     en: 'Rings',     ar: 'خواتم',  image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&q=80' },
      { slug: 'sunglasses',en: 'Sunglasses',ar: 'نظارات', image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80' },
    ],
  },
  featured_section: { tag_en: 'Best Sellers', tag_ar: 'الأكثر مبيعاً', title_en: 'Most Loved Pieces', title_ar: 'الأكثر حباً' },
  shop_our_looks: {
    visible: true,
    tag_en: 'Get The Look', tag_ar: 'احصلي على الإطلالة',
    title_en: 'Shop Our Looks', title_ar: 'تسوقي إطلالاتنا',
    items: [
      { image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80', caption_en: 'Everyday Gold',    caption_ar: 'ذهب يومي',       href: '/products?category=bracelets' },
      { image: 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?w=600&q=80', caption_en: 'Layered Look',     caption_ar: 'إطلالة متطبقة',   href: '/products?category=necklaces' },
      { image: 'https://images.unsplash.com/photo-1577803645773-f96470509666?w=600&q=80', caption_en: 'Statement Ring',   caption_ar: 'خاتم جريء',       href: '/products?category=rings' },
      { image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=80', caption_en: 'Sun-Ready',        caption_ar: 'جاهزة للشمس',     href: '/products?category=sunglasses' },
      { image: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=600&q=80', caption_en: 'Stacked Bracelets',caption_ar: 'أساور متراكمة',   href: '/products?category=bracelets' },
    ],
  },
  editorial_section: {
    tag_en: 'Our Promise', tag_ar: 'وعدنا',
    heading_en: 'Crafted for the\nModern Egyptian Woman',
    heading_ar: 'مصنوع للمرأة\nالمصرية العصرية',
    text_en: 'Every piece in our collection is chosen for its quality, craftsmanship, and ability to elevate your everyday look — from the boardroom to a Cairo evening out.',
    text_ar: 'كل قطعة في مجموعتنا مختارة بعناية للجودة والأناقة — من المكتب لسهرة القاهرة.',
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=900&q=80',
    promise_items: [
      { en: 'Cash on Delivery', ar: 'دفع عند الاستلام' },
      { en: 'Ships Nationwide', ar: 'شحن لكل مصر' },
      { en: 'Quality Guarantee', ar: 'ضمان الجودة' },
      { en: '7-Day Returns',    ar: 'إرجاع ٧ أيام' },
    ],
  },
  cod_banner: {
    tag_en: 'Free Delivery', tag_ar: 'توصيل مجاني',
    heading_ar: 'الدفع عند الاستلام\nلجميع المحافظات',
    text_en: 'Order with complete confidence — pay cash when your parcel arrives at your door, anywhere in Egypt.',
    text_ar: 'اطلبي بكل أمان وادفعي لما البضاعة توصلك — لجميع محافظات مصر',
    cta_en: 'Shop The Collection', cta_ar: 'تسوق المجموعة',
  },
  newsletter_section: {
    tag_en: 'Stay in the loop', tag_ar: 'ابقي على اطلاع',
    heading_en: 'New arrivals, first.', heading_ar: 'الجديد أولاً.',
    subtext_ar: 'اشتركي وكوني أول من يعرف بالعروض والمنتجات الجديدة',
    note_ar: 'لا سبام — نوصلك بس بأهم الأخبار',
  },
  footer: {
    brand_desc_en: 'Premium accessories for the modern Egyptian woman.',
    brand_desc_ar: 'إكسسوارات فاخرة للمرأة المصرية العصرية.',
    whatsapp: '+201234567890',
    email: 'support@accessory.eg',
    location_en: 'Cairo, Egypt', location_ar: 'القاهرة، مصر',
    hours_ar: 'واتساب — السبت–الخميس ١٠ص–١٠م',
    instagram: 'https://instagram.com/accessory.eg',
    facebook: 'https://facebook.com/accessory.eg',
    shop_links: [
      { href: '/products?category=bracelets', label: 'Bracelets' },
      { href: '/products?category=necklaces', label: 'Necklaces' },
      { href: '/products?category=rings',     label: 'Rings' },
      { href: '/products?category=sunglasses',label: 'Sunglasses' },
      { href: '/products?sort=sale',          label: 'Sale' },
    ],
    help_links: [
      { href: '/account',  label: 'My Account' },
      { href: '/checkout', label: 'Checkout' },
      { href: '/returns',  label: 'Returns & Exchanges' },
      { href: '/shipping', label: 'Shipping Policy' },
      { href: '/privacy',  label: 'Privacy Policy' },
    ],
  },
  reviews: [
    { id: 1, name: 'منى إبراهيم',  city: 'القاهرة',    rating: 5, comment: 'والله البضاعة روعة! الأسورة وصلت في كيس فاخر جداً والشغل محكم. أحسن من اللي توقعته بكتير.', date: '٥ أبريل ٢٠٢٤',    product: 'Gold Chain Bracelet', verified: true },
    { id: 2, name: 'سارة محمد',    city: 'الإسكندرية', rating: 5, comment: 'القلادة تحفة فعلاً، اتهدت لي من أختي وانبهرت باللي شوفته. الذهب اللون ثابت ومش بيتأثر بالمياه.', date: '١٢ مارس ٢٠٢٤',   product: 'Pearl Drop Necklace', verified: true },
    { id: 3, name: 'دينا علي',     city: 'الجيزة',     rating: 5, comment: 'خير ما شوفت متجر سريع في التوصيل وأمين! طلبت الخاتم يوم الاتنين ووصل الأربعاء.', date: '٢٠ فبراير ٢٠٢٤', product: 'Statement Ring',      verified: true },
    { id: 4, name: 'ريم عبد الله', city: 'المنصورة',   rating: 5, comment: 'النظارات الشمسية أنيقة جداً ومريحة على الوجه. السعر معقول جداً على الجودة دي.', date: '٨ يناير ٢٠٢٤',    product: 'Vintage Sunglasses',  verified: true },
    { id: 5, name: 'نور حسن',      city: 'أسيوط',      rating: 5, comment: 'أول مرة أشتري اونلاين وكنت خايفة، بس الحمد لله التجربة كانت ممتازة. دفعت عند الاستلام.', date: '٢٥ ديسمبر ٢٠٢٣', product: 'Gold Bangle Set',     verified: true },
    { id: 6, name: 'مريم خالد',    city: 'طنطا',       rating: 4, comment: 'إكسسوارات جميلة ومميزة. التوصيل وصل في الموعد وخدمة العملاء كانت متعاونة جداً.', date: '١٤ نوفمبر ٢٠٢٣', product: 'Silver Choker',       verified: true },
  ],
};
